### ISSUE TITLE
Upgrade to 2.6.1

### ISSUE THREAD

**Issue by andreasdot** [sherlok/ruta-ontologies#1]
Hello Renaud, 
do you have any plans of upgrading the ruta-ontolgies project to work with ruta version 2.6.1?
That would be great!
Best regards,
Andreas.

**Comment by renaud** [comment]
hey Andreas,
sorry i’m not working on this project anymore. but feel free to fork it &
send me a pull request…
good luck, Renaud

**Comment by andreasdot** [comment]
Solved by merging pull request #2.
